#ifndef MAIN_H
#define MAIN_H
#include <stdio.h>
#include "sdkconfig.h"
#include "esp_chip_info.h"
#include "esp_system.h"
#include "esp_mac.h"
#include "esp_wifi.h"
#include "nvs_flash.h"
#include "lwip/inet.h"
#include "wifi_config_local.h"
#include "esp_http_client.h"
#include "cJSON.h"
#include "globals.h"
#include "websocket_client_handler.h"
#include "start_websocket.h"
#include "http_event_handler.h"
#include "http_task.h"
#include "mqtt_startups.h"
#include "wifi_event_handler.h"
#include "ip_event_handler.h"
#include "wifi_startups.h"
#endif